### ISSUE TITLE
docs say to use snake_case but initial pages/components use kebab-case

### ISSUE THREAD

**Issue by daem0ndev** [jadjoubran/laravel5-angular-material-starter#360]
- **I'm submitting a ...**
- [x] bug report
- [x] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**

When following the documentation it says to use snake_case when using the generators, but that breaks consistency with the components/pages that come out of the box in the starter, such as forgot-password, register-form, reset-password, etc. 

I suggest maybe supporting input of snake_case but have the generator automatically convert to kebab-case for the filesystem to match the out of the box components and pages.

Also, definitely take a look at a project I contribute to called [ng6-cli](https://github.com/UltimateSoftware/ng6-cli) which could be used and wrapped by the generators in your package. It handles alot of the same things you're trying to do, but even goes a step farther in how it updates all of your file references. 
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment]
Hi @daem0ndev 
Thanks for this!

Indeed, I'll fix the documentation to mention that they should be kebab-case
However there's no need restricting people to use kebab case if they prefer snake_case

ng6-cli seems very cool! Would you be able to point out some of the stuff that are missing but you might find useful for this starter?
Although for the release after 3.3, we'll be using the official ng-cli for sure (for angular 2)

**Comment by jadjoubran** [comment]
Fixed the docs, thanks!

**Comment by daem0ndev** [comment]
The examples still show like user_profile instead of user-profile :)

**Comment by jadjoubran** [comment]
@daem0ndev Thanks 😄 fixed!
