### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by rizwansultan88** [jadjoubran/laravel5-angular-material-starter#503]
After following complete instructions getting that error trying to install that package but not worked can you help me to sort out that issue.

D:\wamp64\www\laravel\laravel5-angular-material-starter>gulp && gulp watch
module.js:540
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\wamp64\www\laravel\laravel5-angular-material-starter\gulpfile.js:3:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by jadjoubran** [comment]
Hi @rizwansultan88 
I just followed the instructions on the [docs](https://laravel-angular.readme.io/docs) and they are working

Are you sure you ran `npm install`?

**Comment by rizwansultan88** [comment]
Yes I tried npm install and npm update as well but no luck I'm following same you wrote in document both method also tried to install laravel-elixir separately but still no luck.

**Comment by rizwansultan88** [comment]
On my system Operating System Windows 10

**Comment by jadjoubran** [comment]
That's weird, can you give me your `node` and `npm` versions?

**Comment by rizwansultan88** [comment]
![image](https://user-images.githubusercontent.com/5505829/35768085-aab3d57a-0931-11e8-822e-d67fcf511375.png)

**Comment by rizwansultan88** [comment]
npm version 5.6.0
node version 8.9.4

**Comment by jadjoubran** [comment]
please try manually running `npm install laravel-elixir --save-dev`

**Comment by rizwansultan88** [comment]
Still no luck 




D:\wamp64\www\laravelangular\laravel5-angular-material-starter>npm install laravel-elixir --save-dev

> node-sass@3.13.1 install D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v3.13.1/win32-x64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.13.1 postinstall D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\node-sass
> node scripts/build.js

Building: C:\Program Files\nodejs\node.exe D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.4 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:13:12)\n    at F (D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:68:19)\n    at E (D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:80:29)\n    at D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:89:16\n    at D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\isexe\\index.js:42:5\n    at D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` failed Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python { Error: not found: python
gyp verb `which` failed     at getNotFoundError (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:80:29)
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\which\which.js:89:16
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python\n    at getNotFoundError (D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:13:12)\n    at F (D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:68:19)\n    at E (D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:80:29)\n    at D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\which\\which.js:89:16\n    at D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\isexe\\index.js:42:5\n    at D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb could not find "python". checking python launcher
gyp verb could not find "python". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\wamp64\\www\\laravelangular\\laravel5-angular-material-starter\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd D:\wamp64\www\laravelangular\laravel5-angular-material-starter\node_modules\node-sass
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN laravel-elixir-eslint@3.0.2 requires a peer of laravel-elixir@>=3.0.0-0 <6.0.0-0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@3.13.1 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@3.13.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2018-02-06T07_57_35_840Z-debug.log

D:\wamp64\www\laravelangular\laravel5-angular-material-starter>gulp
module.js:540
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\wamp64\www\laravelangular\laravel5-angular-material-starter\gulpfile.js:3:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

D:\wamp64\www\laravelangular\laravel5-angular-material-starter>

**Comment by jadjoubran** [comment]
Based on [this issue](https://github.com/sass/node-sass/issues/1991), please try running:

```
rm -rf node_modules
rm package-lock.json
npm cache clean
npm install
```

**Comment by rizwansultan88** [comment]
Tried but no luck

**Comment by jadjoubran** [comment]
Have you tried running this using another internet connection or maybe even another laptop?

**Comment by rizwansultan88** [comment]
I tried using another internet connection for sure I will tried it in another laptop and let you know.

**Comment by rizwansultan88** [comment]
Installed in another pc and facing same issues

    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (F:\xampp\htdocs\laravelangular\laravel5-angular-material-starter\gulpfile.js:3:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by rizwansultan88** [comment]
I fixed it using composer update command without that it neither be worked.

**Comment by chisumo2016** [comment]
Hi 
I have tried all the above solution but it still not working
module.js:540
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\laragon\www\chisumo-shop\gulpfile.js:2:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by rizwansultan88** [comment]
@chisumo2016 try to execute composer update  command
